gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    single_use: true
    ttl: '%env(int:JWT_REFRESH_TOKEN_TTL)%'
    ttl_update: false
    token_parameter_name: app-%appEnvName%-03b62516184fb6ef591f45bd4974b753 # app.md5('refresh')
    cookie:
        same_site: lax
        domain: '%env(JWT_COOKIE_DOMAIN)%'
    logout_firewall: main
