vich_uploader:
    db_driver: orm
    use_flysystem_to_resolve_uri: true
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: media_storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
