<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250919194409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add MediaObject';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('ALTER TABLE book ADD image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3313DA5256D FOREIGN KEY (image_id) REFERENCES media_object (id)');
        $this->addSql('CREATE INDEX IDX_CBE5A3313DA5256D ON book (image_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE media_object');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3313DA5256D');
        $this->addSql('DROP INDEX IDX_CBE5A3313DA5256D');
        $this->addSql('ALTER TABLE book DROP image_id');
    }
}
